package controller;

public enum Event {
	HIDE_PASSWORD, LOGIN_ACCOUNT, GET_LOGIN_DATA, GET_CREATE_DATA, CANCEL_NEW_ACCOUNT,
	ADD_COURSE_ST, MODIFY_COURSE_ST, DELETE_COURSE_ST,
	ADD_ACTIVITY_ST, MODIFY_ACTIVITY_ST, DELETE_ACTIVITY_ST,
	SHOW_SCHEDULE, ADD_S_TEACHER, ADD_COMBOBOX_COURSE, FIND_TEACHERS, FIND_INFO_ADD_COURSE,
	VISIBLE_TEACHERS, INSERT_COURSE, VISIBLE_SCHEDULE, VISIBLE_HOMEWORK, VISIBLE_MODIFY,
	FIND_HOMEWORK, FIND_INFO_HOMEWORK, ADD_OR_MODIFY_HOMEWORK
	
}
