package controller;

public enum Event {
	HIDE_PASSWORD, LOGIN_ACCOUNT, GET_LOGIN_DATA, CANCEL_NEW_ACCOUNT,
	ADD_COURSE_ST, MODIFY_COURSE_ST, DELETE_COURSE_ST,
	ADD_ACTIVITY_ST, MODIFY_ACTIVITY_ST, DELETE_ACTIVITY_ST,
	SHOW_SCHEDULE
}
