package controller;

public enum Event {
	HIDE_PASSWORD, LOGIN_ACCOUNT, GET_LOGIN_DATA, GET_CREATE_DATA, CANCEL_NEW_ACCOUNT,
	ADD_COURSE_ST, MODIFY_COURSE_ST, DELETE_COURSE_OR_HOMEWORK,
	ADD_OR_MOD_ACTIVITY_ST, AVG_ST, DELETE_ACTIVITY_ST,
	SHOW_SCHEDULE, ADD_S_TEACHER, ADD_COMBOBOX_COURSE, FIND_TEACHERS, FIND_INFO_ADD_COURSE,
	VISIBLE_TEACHERS, INSERT_COURSE, VISIBLE_SCHEDULE, VISIBLE_HOMEWORK, VISIBLE_MODIFY,
	FIND_HOMEWORK, FIND_INFO_HOMEWORK, ADD_OR_MODIFY_HOMEWORK, FIND_HOMEWORK_DELETE, DELETE_COURSE,
	CONFIRM_DELETE_COURSE, CONFIRM_DELETE_HOMEWORK, DELETE_HOMEWORK, FIND_MODIFY_HOMEWORK,
	ADD_OR_MODIFY_ACTIVITY, DELETE_ACTIVITY, CONFIRM_DELETE_ACTIVITY, CALCULATE_AVG
	
}
